USE [master]
GO

/****** Object:  Database [EmailCampaign]    Script Date: 12/16/2013 8:58:59 AM ******/
DROP DATABASE [EmailCampaign]
GO

/****** Object:  Database [EmailCampaign]    Script Date: 12/16/2013 8:58:59 AM ******/
CREATE DATABASE [EmailCampaign]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmailCampaign', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\EmailCampaign.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EmailCampaign_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\EmailCampaign_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EmailCampaign] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmailCampaign].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmailCampaign] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmailCampaign] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmailCampaign] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmailCampaign] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmailCampaign] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmailCampaign] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [EmailCampaign] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [EmailCampaign] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmailCampaign] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmailCampaign] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmailCampaign] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmailCampaign] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmailCampaign] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmailCampaign] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmailCampaign] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmailCampaign] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EmailCampaign] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmailCampaign] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmailCampaign] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmailCampaign] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmailCampaign] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmailCampaign] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmailCampaign] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmailCampaign] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EmailCampaign] SET  MULTI_USER 
GO

ALTER DATABASE [EmailCampaign] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmailCampaign] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmailCampaign] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmailCampaign] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EmailCampaign] SET  READ_WRITE 
GO

